#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

create() {
  heroku create

  heroku addons:add mongohq
  heroku addons:add rediscloud
  heroku addons:add cloudamqp

  heroku config:set SESSION_SECRET="`openssl rand -base64 32`"
  heroku config:set NODE_ENV="production"
  heroku config:set VIEW_CACHE="true"

  git push heroku master
  heroku ps:scale web=1 worker=1
}

create
