#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

create() {
  heroku create
  heroku addons:add mongohq
  heroku addons:add rediscloud
  heroku config:set SESSION_SECRET="`openssl rand -base64 32`"

  heroku config:set NODE_ENV=production
  heroku config:set QUIET=true
  heroku config:unset DEBUG

  git push heroku master
  heroku open
}

create
