#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

scale() {
  heroku addons:upgrade rediscloud:100 &2> /dev/null

  # To stop forking multiple workers: heroku config:unset CONCURRENT
  heroku config:set CONCURRENT=true

  # To scale back down: heroku ps:scale web=1:1X
  heroku ps:scale web=3:2X
}

scale
